men_names = ['Alexander',
             'Andres',
             'Daniel',
             'Javier',
             'Fernando',
             'Sergio',
             'Simon',
             'Carlos',
             'Juan',
             'Jeison',
             'Jonathan',
             'Santiago',
             'David',
             'Alejandro',
             'Sebastian',
             'Ricardo']

men_bios = ['casada',
            'married',
            'bieber',
            'sugardaddy',
            'Transgénero',
            'transgénero',
            'Transgenero',
            'transgenero',
            'transgender',
            'Transgender',
            'Trans',
            'trans',
            'TRANS',
            'Transgirl',
            'transgirl',
            'transexual',
            'Transexual']
   